### ISSUE TITLE
rattrapage liste vide

### ISSUE THREAD

**Issue by Sphinxroot** [anisite/plugin.infologique.TVAgo#16]
allo anisite 

tva+ doivent avoir changer quelque chose  

seulement les lives fonctionnent
les titres d emmissions sont visible mais la liste est vide sans aucune erreur apparente

que ce sois sur leia ou matrix  via windows ou android

si possible de corriger 
merci

**Comment by erikatremblay** [comment]
Je seconde rien n’apparaît

**Comment by erikatremblay** [comment]
Est-ce possible que quelqu’un nous donne une piste sur quoi changer dans le addon ?

**Comment by tatou100** [comment]
C'est probablement la structure du json retourné par le site qui a changé. Il va faloir creuser le site web pour comprendre et corriger. Mais il y a un problème pire depuis. Le plugin refuse même de partir. Donc il va faloir corriger ça avant.

**Comment by erikatremblay** [comment]
Pourtant moi le plugin ouvre 🤔 la seule chose qui se passe est lorsque que je clique sur une émission rien n’apparaît c’est vide

**Comment by tatou100** [comment]
J'ai sortie quelques log. Je reproduit aussi le problème.

Kodi retourne:
2022-09-15 20:01:03.401 T:11672   DEBUG <general>: [TVA+ - DEBUG]: /tva/5-gars-pour-moi
2022-09-15 20:01:03.401 T:11672   DEBUG <general>: [TVA+ - DEBUG]: content.LoadContainerItems
2022-09-15 20:01:03.401 T:11672   DEBUG <general>: [TVA+ - DEBUG]: {'content': {'genreId': 1, 'mediaBundleId': -1, 'afficherTous': False, 'url': '/tva', 'containerId': '/tva/5-gars-pour-moi'}, 'show': {'Saison': '', 'Episode': '', 'label': ''}, 'fullNameItems': [], 'sourceId': ''}
2022-09-15 20:01:03.401 T:11672   DEBUG <general>: [TVA+ - DEBUG]: Accessing: https://api.qub.ca/content-delivery-service/v1/entities?slug=/tva/5-gars-pour-moi
2022-09-15 20:01:03.402 T:11672   DEBUG <CAddonSettings[plugin.infologique.TVAgo]>: trying to load setting definitions from old format...
2022-09-15 20:01:03.403 T:11672   DEBUG <CSettingsManager>: requested setting (NetworkDetection) was not found.
2022-09-15 20:01:03.403 T:11672   DEBUG <CSettingsManager>: requested setting section (plugin.infologique.tvago) was not found.
2022-09-15 20:01:03.403 T:11672   DEBUG <general>: [TVA+ - DEBUG]: html.get_url_txt
2022-09-15 20:01:03.583 T:11672   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 403: Forbidden
                                                   Traceback (most recent call last):
                                                     File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\default.py", line 122, in <module>
                                                       Load()
                                                     File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\default.py", line 19, in Load
                                                       CreateFilteredList()
                                                     File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\default.py", line 37, in CreateFilteredList
                                                       navig.AddItemInMenu(content.LoadContainerItems(filtres))
                                                     File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\resources\lib\content.py", line 134, in LoadContainerItems
                                                       jsonData = json.loads(html.get_url_txt(strURL), encoding='utf-8')
                                                     File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\resources\lib\html.py", line 73, in get_url_txt
                                                       response = urlopen(req)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 403: Forbidden
                                                   -->End of Python script error report<--


Je sais pas vraiment ce qui pourrait causer un erreur 403: Forbidden du serveur par contre. Je vais essayer de voir si je trouve comment corriger ça. Mais je garantie rien.

**Comment by erikatremblay** [comment]
J’ai fouiller un peu il y a 2 jours dans les fichiers du addons et d’après moi c’est le lien source qui n’est plus bon car quand je le prend et le colle sur internet la page n’existe plus 🤷🏼‍♀️

**Comment by tatou100** [comment]
@erikatremblay Il y a effectivement un lien qui semble avoir changé. Je pense avoir trouvé le bon. J'ai aussi changé quelques entente aux requêtes sinon ca semblait se faire refuser. Le plugin se faisait passé pour un vieux navigateur safarie et c'était peut-être trop vieux. J'ai réussi a faire afficher la liste des épisodes. Mais ca joue plus quand on essaie de les partir. Je vais continuer plus tard. 
Mes modifications sont ici pour le moment: https://github.com/anisite/plugin.infologique.TVAgo/tree/bugfix/MainUrlFix

**Comment by erikatremblay** [comment]
@tatou100 good merci m’a essayé de regarder si j’ai le temps voir ce que sa fait dans mon kodi. 

Je suis pas codeuse donc je peux pas full aider malheureusement. 🙈

**Comment by tatou100** [comment]
@erikatremblay Ça semble bien fonctionner pour moi avec mes corrections. Êtes-vous capable de mettre à jour les fichiers content.py, html.py et navig.py a partir d'ici (https://github.com/anisite/plugin.infologique.TVAgo/tree/bugfix/MainUrlFix/resources/lib)  et voir si ca fonctionne maintenant?

**Comment by erikatremblay** [comment]
J’essaye

**Comment by erikatremblay** [comment]
Je ne sais pas comment les mettre à jour est-ce qu'on est mieux d'attendre qu'anisite upgrade avec les changements ? Car sinon je dois j'imagine copier les codes que vous avez changé et les mettre à la place des fichiers que j'ai dans mon plugin?

**Comment by anisite** [comment]
@tatou100 j'ai deleter la branche structure json, trop vite, est-ce que c'était déjà dans ton autre branche du pull request?

**Comment by anisite** [comment]
@erikatremblay la version 2.0.1 vient d'être déployée. tu peux forcer la maj?

**Comment by erikatremblay** [comment]
Yes je test sa dans 1 min

**Comment by erikatremblay** [comment]
Je l’a voit pas donc je ferme mon kodi et réessaye ;)

**Comment by erikatremblay** [comment]
Je l’a voit vraiment pas de disponible la 2.0.1 
J’ai juste la 2.0.0 et elle fonctionne pu 🙈 
Je restart ma beelink des fois 🤷🏼‍♀️
sans succès je ne l’a voit pas malheureusement

**Comment by erikatremblay** [comment]
![Uploading image.jpg…]()

**Comment by erikatremblay** [comment]
Elle vient d’apparaître 👌

**Comment by erikatremblay** [comment]
Sa marche !! Alléluia! 👌☺️😏

**Comment by anisite** [comment]
il faut remercier @tatou100

**Comment by erikatremblay** [comment]
Ohhh oui, pas d’inquiétude 😉 merci infiniment @tatou100 🙌

**Comment by tatou100** [comment]
@anisite pour la vieille branch "structure json", oui ca va j'avais partie de celle là. 
@erikatremblay De rien!

**Comment by tatou100** [comment]
fixé dans 2.0.1 :)

**Comment by Sphinxroot** [comment]
ca fonctionne mais jai une erreur skin helper sur evasion , tva sport  et zeste

**Comment by tatou100** [comment]
@Sphinxroot Effectivement ceux la ne fonctionne pas. j'avais pas fait le tour de ceux là.

**Comment by tatou100** [comment]
J'ai trouvé quelques autres bugs en même temps. Ça va être corrigé dans la prochaine version ou vous pouvez updater ce fichier https://raw.githubusercontent.com/anisite/plugin.infologique.TVAgo/master/resources/lib/content.py
- Corrige Zeste,TVA sport et Evasion qui ne marchait plus.
- Enleve les items qui ne sont pas des emissions (comme des nouvelles de sport).
- Corrige les emissions qui etaient vide parce qu'ils n'ont pas de saison. Comme les emissions d'humour.

**Comment by tatou100** [comment]
J'utilise les modifs depuis et tout semble bien marcher. Il reste a le mettre à jour dans DepotQuébec. @anisite

**Comment by anisite** [comment]
c'est fait
