### ISSUE TITLE
Erreur quand on entre dans le menu principal du plugin TVA

### ISSUE THREAD

**Issue by tatou100** [anisite/plugin.infologique.TVAgo#17]
Il n'est meme plus possible d'accéder au plugin.

`2022-09-15 19:37:36.956 T:17756   ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2022-09-15 19:37:36.973 T:19012    INFO <general>: initializing python engine.
2022-09-15 19:37:37.621 T:19012 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-09-15 19:37:38.164 T:19012   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 404: Not Found
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Math\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\default.py", line 122, in <module>
                                                       Load()
                                                     File "C:\Users\Math\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\default.py", line 21, in Load
                                                       CreateMainMenu()
                                                     File "C:\Users\Math\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\default.py", line 27, in CreateMainMenu
                                                       navig.AddItemInMenu(content.LoadMainMenu(filtres))
                                                     File "C:\Users\Math\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\resources\lib\content.py", line 195, in LoadMainMenu
                                                       jsonConfig = json.loads(html.get_url_txt(strURL, False), encoding='utf-8')
                                                     File "C:\Users\Math\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\resources\lib\html.py", line 73, in get_url_txt
                                                       response = urlopen(req)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 404: Not Found
                                                   -->End of Python script error report<--
                                                   
2022-09-15 19:37:38.166 T:6244     INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-09-15 19:37:38.261 T:19012    INFO <general>: Python interpreter stopped
2022-09-15 19:37:38.261 T:15172   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.infologique.TVAgo/
2022-09-15 19:37:38.266 T:17756   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.TVAgo/) failed
`

**Comment by tatou100** [comment]
Fixé dans version 2.0.1
